// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatserver.proto

package io.leego.chat.core;

/**
 * Protobuf type {@code chatserver.Instance}
 */
public final class Instance extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:chatserver.Instance)
    InstanceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Instance.newBuilder() to construct.
  private Instance(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Instance() {
    host_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Instance();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.leego.chat.core.ChatFactory.internal_static_chatserver_Instance_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.leego.chat.core.ChatFactory.internal_static_chatserver_Instance_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.leego.chat.core.Instance.class, io.leego.chat.core.Instance.Builder.class);
  }

  public static final int NODE_FIELD_NUMBER = 1;
  private int node_ = 0;
  /**
   * <code>int32 node = 1;</code>
   * @return The node.
   */
  @java.lang.Override
  public int getNode() {
    return node_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 2;
  private long timestamp_ = 0L;
  /**
   * <code>int64 timestamp = 2;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int HOST_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object host_ = "";
  /**
   * <code>string host = 3;</code>
   * @return The host.
   */
  @java.lang.Override
  public java.lang.String getHost() {
    java.lang.Object ref = host_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      host_ = s;
      return s;
    }
  }
  /**
   * <code>string host = 3;</code>
   * @return The bytes for host.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHostBytes() {
    java.lang.Object ref = host_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      host_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISCOVERYPORT_FIELD_NUMBER = 4;
  private int discoveryPort_ = 0;
  /**
   * <code>int32 discoveryPort = 4;</code>
   * @return The discoveryPort.
   */
  @java.lang.Override
  public int getDiscoveryPort() {
    return discoveryPort_;
  }

  public static final int RAWPORT_FIELD_NUMBER = 5;
  private int rawPort_ = 0;
  /**
   * <code>int32 rawPort = 5;</code>
   * @return The rawPort.
   */
  @java.lang.Override
  public int getRawPort() {
    return rawPort_;
  }

  public static final int WSPORT_FIELD_NUMBER = 6;
  private int wsPort_ = 0;
  /**
   * <code>int32 wsPort = 6;</code>
   * @return The wsPort.
   */
  @java.lang.Override
  public int getWsPort() {
    return wsPort_;
  }

  public static final int CLIENTS_FIELD_NUMBER = 7;
  private int clients_ = 0;
  /**
   * <code>int32 clients = 7;</code>
   * @return The clients.
   */
  @java.lang.Override
  public int getClients() {
    return clients_;
  }

  public static final int LEADERS_FIELD_NUMBER = 8;
  private int leaders_ = 0;
  /**
   * <code>int32 leaders = 8;</code>
   * @return The leaders.
   */
  @java.lang.Override
  public int getLeaders() {
    return leaders_;
  }

  public static final int FOLLOWERS_FIELD_NUMBER = 9;
  private int followers_ = 0;
  /**
   * <code>int32 followers = 9;</code>
   * @return The followers.
   */
  @java.lang.Override
  public int getFollowers() {
    return followers_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (node_ != 0) {
      output.writeInt32(1, node_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(2, timestamp_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(host_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, host_);
    }
    if (discoveryPort_ != 0) {
      output.writeInt32(4, discoveryPort_);
    }
    if (rawPort_ != 0) {
      output.writeInt32(5, rawPort_);
    }
    if (wsPort_ != 0) {
      output.writeInt32(6, wsPort_);
    }
    if (clients_ != 0) {
      output.writeInt32(7, clients_);
    }
    if (leaders_ != 0) {
      output.writeInt32(8, leaders_);
    }
    if (followers_ != 0) {
      output.writeInt32(9, followers_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (node_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, node_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, timestamp_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(host_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, host_);
    }
    if (discoveryPort_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, discoveryPort_);
    }
    if (rawPort_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, rawPort_);
    }
    if (wsPort_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, wsPort_);
    }
    if (clients_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, clients_);
    }
    if (leaders_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, leaders_);
    }
    if (followers_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, followers_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.leego.chat.core.Instance)) {
      return super.equals(obj);
    }
    io.leego.chat.core.Instance other = (io.leego.chat.core.Instance) obj;

    if (getNode()
        != other.getNode()) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!getHost()
        .equals(other.getHost())) return false;
    if (getDiscoveryPort()
        != other.getDiscoveryPort()) return false;
    if (getRawPort()
        != other.getRawPort()) return false;
    if (getWsPort()
        != other.getWsPort()) return false;
    if (getClients()
        != other.getClients()) return false;
    if (getLeaders()
        != other.getLeaders()) return false;
    if (getFollowers()
        != other.getFollowers()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NODE_FIELD_NUMBER;
    hash = (53 * hash) + getNode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (37 * hash) + HOST_FIELD_NUMBER;
    hash = (53 * hash) + getHost().hashCode();
    hash = (37 * hash) + DISCOVERYPORT_FIELD_NUMBER;
    hash = (53 * hash) + getDiscoveryPort();
    hash = (37 * hash) + RAWPORT_FIELD_NUMBER;
    hash = (53 * hash) + getRawPort();
    hash = (37 * hash) + WSPORT_FIELD_NUMBER;
    hash = (53 * hash) + getWsPort();
    hash = (37 * hash) + CLIENTS_FIELD_NUMBER;
    hash = (53 * hash) + getClients();
    hash = (37 * hash) + LEADERS_FIELD_NUMBER;
    hash = (53 * hash) + getLeaders();
    hash = (37 * hash) + FOLLOWERS_FIELD_NUMBER;
    hash = (53 * hash) + getFollowers();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.leego.chat.core.Instance parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.leego.chat.core.Instance parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.leego.chat.core.Instance parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.leego.chat.core.Instance parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.leego.chat.core.Instance parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.leego.chat.core.Instance parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.leego.chat.core.Instance parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.leego.chat.core.Instance parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.leego.chat.core.Instance parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.leego.chat.core.Instance parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.leego.chat.core.Instance parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.leego.chat.core.Instance parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.leego.chat.core.Instance prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code chatserver.Instance}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:chatserver.Instance)
      io.leego.chat.core.InstanceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.leego.chat.core.ChatFactory.internal_static_chatserver_Instance_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.leego.chat.core.ChatFactory.internal_static_chatserver_Instance_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.leego.chat.core.Instance.class, io.leego.chat.core.Instance.Builder.class);
    }

    // Construct using io.leego.chat.core.Instance.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      node_ = 0;
      timestamp_ = 0L;
      host_ = "";
      discoveryPort_ = 0;
      rawPort_ = 0;
      wsPort_ = 0;
      clients_ = 0;
      leaders_ = 0;
      followers_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.leego.chat.core.ChatFactory.internal_static_chatserver_Instance_descriptor;
    }

    @java.lang.Override
    public io.leego.chat.core.Instance getDefaultInstanceForType() {
      return io.leego.chat.core.Instance.getDefaultInstance();
    }

    @java.lang.Override
    public io.leego.chat.core.Instance build() {
      io.leego.chat.core.Instance result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.leego.chat.core.Instance buildPartial() {
      io.leego.chat.core.Instance result = new io.leego.chat.core.Instance(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.leego.chat.core.Instance result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.node_ = node_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.timestamp_ = timestamp_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.host_ = host_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.discoveryPort_ = discoveryPort_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.rawPort_ = rawPort_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.wsPort_ = wsPort_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.clients_ = clients_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.leaders_ = leaders_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.followers_ = followers_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.leego.chat.core.Instance) {
        return mergeFrom((io.leego.chat.core.Instance)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.leego.chat.core.Instance other) {
      if (other == io.leego.chat.core.Instance.getDefaultInstance()) return this;
      if (other.getNode() != 0) {
        setNode(other.getNode());
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (!other.getHost().isEmpty()) {
        host_ = other.host_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getDiscoveryPort() != 0) {
        setDiscoveryPort(other.getDiscoveryPort());
      }
      if (other.getRawPort() != 0) {
        setRawPort(other.getRawPort());
      }
      if (other.getWsPort() != 0) {
        setWsPort(other.getWsPort());
      }
      if (other.getClients() != 0) {
        setClients(other.getClients());
      }
      if (other.getLeaders() != 0) {
        setLeaders(other.getLeaders());
      }
      if (other.getFollowers() != 0) {
        setFollowers(other.getFollowers());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              node_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              timestamp_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              host_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              discoveryPort_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              rawPort_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              wsPort_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              clients_ = input.readInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              leaders_ = input.readInt32();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              followers_ = input.readInt32();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int node_ ;
    /**
     * <code>int32 node = 1;</code>
     * @return The node.
     */
    @java.lang.Override
    public int getNode() {
      return node_;
    }
    /**
     * <code>int32 node = 1;</code>
     * @param value The node to set.
     * @return This builder for chaining.
     */
    public Builder setNode(int value) {
      
      node_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 node = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNode() {
      bitField0_ = (bitField0_ & ~0x00000001);
      node_ = 0;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 2;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 2;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000002);
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object host_ = "";
    /**
     * <code>string host = 3;</code>
     * @return The host.
     */
    public java.lang.String getHost() {
      java.lang.Object ref = host_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        host_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string host = 3;</code>
     * @return The bytes for host.
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      java.lang.Object ref = host_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string host = 3;</code>
     * @param value The host to set.
     * @return This builder for chaining.
     */
    public Builder setHost(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      host_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string host = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearHost() {
      host_ = getDefaultInstance().getHost();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string host = 3;</code>
     * @param value The bytes for host to set.
     * @return This builder for chaining.
     */
    public Builder setHostBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      host_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int discoveryPort_ ;
    /**
     * <code>int32 discoveryPort = 4;</code>
     * @return The discoveryPort.
     */
    @java.lang.Override
    public int getDiscoveryPort() {
      return discoveryPort_;
    }
    /**
     * <code>int32 discoveryPort = 4;</code>
     * @param value The discoveryPort to set.
     * @return This builder for chaining.
     */
    public Builder setDiscoveryPort(int value) {
      
      discoveryPort_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 discoveryPort = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDiscoveryPort() {
      bitField0_ = (bitField0_ & ~0x00000008);
      discoveryPort_ = 0;
      onChanged();
      return this;
    }

    private int rawPort_ ;
    /**
     * <code>int32 rawPort = 5;</code>
     * @return The rawPort.
     */
    @java.lang.Override
    public int getRawPort() {
      return rawPort_;
    }
    /**
     * <code>int32 rawPort = 5;</code>
     * @param value The rawPort to set.
     * @return This builder for chaining.
     */
    public Builder setRawPort(int value) {
      
      rawPort_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int32 rawPort = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearRawPort() {
      bitField0_ = (bitField0_ & ~0x00000010);
      rawPort_ = 0;
      onChanged();
      return this;
    }

    private int wsPort_ ;
    /**
     * <code>int32 wsPort = 6;</code>
     * @return The wsPort.
     */
    @java.lang.Override
    public int getWsPort() {
      return wsPort_;
    }
    /**
     * <code>int32 wsPort = 6;</code>
     * @param value The wsPort to set.
     * @return This builder for chaining.
     */
    public Builder setWsPort(int value) {
      
      wsPort_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 wsPort = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearWsPort() {
      bitField0_ = (bitField0_ & ~0x00000020);
      wsPort_ = 0;
      onChanged();
      return this;
    }

    private int clients_ ;
    /**
     * <code>int32 clients = 7;</code>
     * @return The clients.
     */
    @java.lang.Override
    public int getClients() {
      return clients_;
    }
    /**
     * <code>int32 clients = 7;</code>
     * @param value The clients to set.
     * @return This builder for chaining.
     */
    public Builder setClients(int value) {
      
      clients_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int32 clients = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearClients() {
      bitField0_ = (bitField0_ & ~0x00000040);
      clients_ = 0;
      onChanged();
      return this;
    }

    private int leaders_ ;
    /**
     * <code>int32 leaders = 8;</code>
     * @return The leaders.
     */
    @java.lang.Override
    public int getLeaders() {
      return leaders_;
    }
    /**
     * <code>int32 leaders = 8;</code>
     * @param value The leaders to set.
     * @return This builder for chaining.
     */
    public Builder setLeaders(int value) {
      
      leaders_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>int32 leaders = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearLeaders() {
      bitField0_ = (bitField0_ & ~0x00000080);
      leaders_ = 0;
      onChanged();
      return this;
    }

    private int followers_ ;
    /**
     * <code>int32 followers = 9;</code>
     * @return The followers.
     */
    @java.lang.Override
    public int getFollowers() {
      return followers_;
    }
    /**
     * <code>int32 followers = 9;</code>
     * @param value The followers to set.
     * @return This builder for chaining.
     */
    public Builder setFollowers(int value) {
      
      followers_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>int32 followers = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearFollowers() {
      bitField0_ = (bitField0_ & ~0x00000100);
      followers_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:chatserver.Instance)
  }

  // @@protoc_insertion_point(class_scope:chatserver.Instance)
  private static final io.leego.chat.core.Instance DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.leego.chat.core.Instance();
  }

  public static io.leego.chat.core.Instance getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Instance>
      PARSER = new com.google.protobuf.AbstractParser<Instance>() {
    @java.lang.Override
    public Instance parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Instance> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Instance> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.leego.chat.core.Instance getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

