// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatserver.proto

package io.leego.chat.core;

public interface InstanceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chatserver.Instance)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 node = 1;</code>
   * @return The node.
   */
  int getNode();

  /**
   * <code>int64 timestamp = 2;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>string host = 3;</code>
   * @return The host.
   */
  java.lang.String getHost();
  /**
   * <code>string host = 3;</code>
   * @return The bytes for host.
   */
  com.google.protobuf.ByteString
      getHostBytes();

  /**
   * <code>int32 discoveryPort = 4;</code>
   * @return The discoveryPort.
   */
  int getDiscoveryPort();

  /**
   * <code>int32 rawPort = 5;</code>
   * @return The rawPort.
   */
  int getRawPort();

  /**
   * <code>int32 wsPort = 6;</code>
   * @return The wsPort.
   */
  int getWsPort();

  /**
   * <code>int32 clients = 7;</code>
   * @return The clients.
   */
  int getClients();

  /**
   * <code>int32 leaders = 8;</code>
   * @return The leaders.
   */
  int getLeaders();

  /**
   * <code>int32 followers = 9;</code>
   * @return The followers.
   */
  int getFollowers();
}
