// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatserver.proto

package io.leego.chat.core;

public interface PacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chatserver.Packet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.chatserver.Box box = 1;</code>
   * @return Whether the box field is set.
   */
  boolean hasBox();
  /**
   * <code>.chatserver.Box box = 1;</code>
   * @return The box.
   */
  io.leego.chat.core.Box getBox();
  /**
   * <code>.chatserver.Box box = 1;</code>
   */
  io.leego.chat.core.BoxOrBuilder getBoxOrBuilder();

  /**
   * <code>repeated int64 target = 2;</code>
   * @return A list containing the target.
   */
  java.util.List<java.lang.Long> getTargetList();
  /**
   * <code>repeated int64 target = 2;</code>
   * @return The count of target.
   */
  int getTargetCount();
  /**
   * <code>repeated int64 target = 2;</code>
   * @param index The index of the element to return.
   * @return The target at the given index.
   */
  long getTarget(int index);

  /**
   * <code>repeated int32 client = 3;</code>
   * @return A list containing the client.
   */
  java.util.List<java.lang.Integer> getClientList();
  /**
   * <code>repeated int32 client = 3;</code>
   * @return The count of client.
   */
  int getClientCount();
  /**
   * <code>repeated int32 client = 3;</code>
   * @param index The index of the element to return.
   * @return The client at the given index.
   */
  int getClient(int index);
}
