// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatserver.proto

package io.leego.chat.core;

/**
 * Protobuf type {@code chatserver.Packet}
 */
public final class Packet extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:chatserver.Packet)
    PacketOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Packet.newBuilder() to construct.
  private Packet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Packet() {
    target_ = emptyLongList();
    client_ = emptyIntList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Packet();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.leego.chat.core.ChatFactory.internal_static_chatserver_Packet_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.leego.chat.core.ChatFactory.internal_static_chatserver_Packet_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.leego.chat.core.Packet.class, io.leego.chat.core.Packet.Builder.class);
  }

  public static final int BOX_FIELD_NUMBER = 1;
  private io.leego.chat.core.Box box_;
  /**
   * <code>.chatserver.Box box = 1;</code>
   * @return Whether the box field is set.
   */
  @java.lang.Override
  public boolean hasBox() {
    return box_ != null;
  }
  /**
   * <code>.chatserver.Box box = 1;</code>
   * @return The box.
   */
  @java.lang.Override
  public io.leego.chat.core.Box getBox() {
    return box_ == null ? io.leego.chat.core.Box.getDefaultInstance() : box_;
  }
  /**
   * <code>.chatserver.Box box = 1;</code>
   */
  @java.lang.Override
  public io.leego.chat.core.BoxOrBuilder getBoxOrBuilder() {
    return box_ == null ? io.leego.chat.core.Box.getDefaultInstance() : box_;
  }

  public static final int TARGET_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.LongList target_;
  /**
   * <code>repeated int64 target = 2;</code>
   * @return A list containing the target.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getTargetList() {
    return target_;
  }
  /**
   * <code>repeated int64 target = 2;</code>
   * @return The count of target.
   */
  public int getTargetCount() {
    return target_.size();
  }
  /**
   * <code>repeated int64 target = 2;</code>
   * @param index The index of the element to return.
   * @return The target at the given index.
   */
  public long getTarget(int index) {
    return target_.getLong(index);
  }
  private int targetMemoizedSerializedSize = -1;

  public static final int CLIENT_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.IntList client_;
  /**
   * <code>repeated int32 client = 3;</code>
   * @return A list containing the client.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getClientList() {
    return client_;
  }
  /**
   * <code>repeated int32 client = 3;</code>
   * @return The count of client.
   */
  public int getClientCount() {
    return client_.size();
  }
  /**
   * <code>repeated int32 client = 3;</code>
   * @param index The index of the element to return.
   * @return The client at the given index.
   */
  public int getClient(int index) {
    return client_.getInt(index);
  }
  private int clientMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (box_ != null) {
      output.writeMessage(1, getBox());
    }
    if (getTargetList().size() > 0) {
      output.writeUInt32NoTag(18);
      output.writeUInt32NoTag(targetMemoizedSerializedSize);
    }
    for (int i = 0; i < target_.size(); i++) {
      output.writeInt64NoTag(target_.getLong(i));
    }
    if (getClientList().size() > 0) {
      output.writeUInt32NoTag(26);
      output.writeUInt32NoTag(clientMemoizedSerializedSize);
    }
    for (int i = 0; i < client_.size(); i++) {
      output.writeInt32NoTag(client_.getInt(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (box_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBox());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < target_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(target_.getLong(i));
      }
      size += dataSize;
      if (!getTargetList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      targetMemoizedSerializedSize = dataSize;
    }
    {
      int dataSize = 0;
      for (int i = 0; i < client_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(client_.getInt(i));
      }
      size += dataSize;
      if (!getClientList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      clientMemoizedSerializedSize = dataSize;
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.leego.chat.core.Packet)) {
      return super.equals(obj);
    }
    io.leego.chat.core.Packet other = (io.leego.chat.core.Packet) obj;

    if (hasBox() != other.hasBox()) return false;
    if (hasBox()) {
      if (!getBox()
          .equals(other.getBox())) return false;
    }
    if (!getTargetList()
        .equals(other.getTargetList())) return false;
    if (!getClientList()
        .equals(other.getClientList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBox()) {
      hash = (37 * hash) + BOX_FIELD_NUMBER;
      hash = (53 * hash) + getBox().hashCode();
    }
    if (getTargetCount() > 0) {
      hash = (37 * hash) + TARGET_FIELD_NUMBER;
      hash = (53 * hash) + getTargetList().hashCode();
    }
    if (getClientCount() > 0) {
      hash = (37 * hash) + CLIENT_FIELD_NUMBER;
      hash = (53 * hash) + getClientList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.leego.chat.core.Packet parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.leego.chat.core.Packet parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.leego.chat.core.Packet parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.leego.chat.core.Packet parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.leego.chat.core.Packet parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.leego.chat.core.Packet parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.leego.chat.core.Packet parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.leego.chat.core.Packet parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.leego.chat.core.Packet parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.leego.chat.core.Packet parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.leego.chat.core.Packet parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.leego.chat.core.Packet parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.leego.chat.core.Packet prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code chatserver.Packet}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:chatserver.Packet)
      io.leego.chat.core.PacketOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.leego.chat.core.ChatFactory.internal_static_chatserver_Packet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.leego.chat.core.ChatFactory.internal_static_chatserver_Packet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.leego.chat.core.Packet.class, io.leego.chat.core.Packet.Builder.class);
    }

    // Construct using io.leego.chat.core.Packet.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      box_ = null;
      if (boxBuilder_ != null) {
        boxBuilder_.dispose();
        boxBuilder_ = null;
      }
      target_ = emptyLongList();
      client_ = emptyIntList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.leego.chat.core.ChatFactory.internal_static_chatserver_Packet_descriptor;
    }

    @java.lang.Override
    public io.leego.chat.core.Packet getDefaultInstanceForType() {
      return io.leego.chat.core.Packet.getDefaultInstance();
    }

    @java.lang.Override
    public io.leego.chat.core.Packet build() {
      io.leego.chat.core.Packet result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.leego.chat.core.Packet buildPartial() {
      io.leego.chat.core.Packet result = new io.leego.chat.core.Packet(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.leego.chat.core.Packet result) {
      if (((bitField0_ & 0x00000002) != 0)) {
        target_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.target_ = target_;
      if (((bitField0_ & 0x00000004) != 0)) {
        client_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.client_ = client_;
    }

    private void buildPartial0(io.leego.chat.core.Packet result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.box_ = boxBuilder_ == null
            ? box_
            : boxBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.leego.chat.core.Packet) {
        return mergeFrom((io.leego.chat.core.Packet)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.leego.chat.core.Packet other) {
      if (other == io.leego.chat.core.Packet.getDefaultInstance()) return this;
      if (other.hasBox()) {
        mergeBox(other.getBox());
      }
      if (!other.target_.isEmpty()) {
        if (target_.isEmpty()) {
          target_ = other.target_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureTargetIsMutable();
          target_.addAll(other.target_);
        }
        onChanged();
      }
      if (!other.client_.isEmpty()) {
        if (client_.isEmpty()) {
          client_ = other.client_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureClientIsMutable();
          client_.addAll(other.client_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getBoxFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              long v = input.readInt64();
              ensureTargetIsMutable();
              target_.addLong(v);
              break;
            } // case 16
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureTargetIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                target_.addLong(input.readInt64());
              }
              input.popLimit(limit);
              break;
            } // case 18
            case 24: {
              int v = input.readInt32();
              ensureClientIsMutable();
              client_.addInt(v);
              break;
            } // case 24
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureClientIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                client_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private io.leego.chat.core.Box box_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.leego.chat.core.Box, io.leego.chat.core.Box.Builder, io.leego.chat.core.BoxOrBuilder> boxBuilder_;
    /**
     * <code>.chatserver.Box box = 1;</code>
     * @return Whether the box field is set.
     */
    public boolean hasBox() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.chatserver.Box box = 1;</code>
     * @return The box.
     */
    public io.leego.chat.core.Box getBox() {
      if (boxBuilder_ == null) {
        return box_ == null ? io.leego.chat.core.Box.getDefaultInstance() : box_;
      } else {
        return boxBuilder_.getMessage();
      }
    }
    /**
     * <code>.chatserver.Box box = 1;</code>
     */
    public Builder setBox(io.leego.chat.core.Box value) {
      if (boxBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        box_ = value;
      } else {
        boxBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.chatserver.Box box = 1;</code>
     */
    public Builder setBox(
        io.leego.chat.core.Box.Builder builderForValue) {
      if (boxBuilder_ == null) {
        box_ = builderForValue.build();
      } else {
        boxBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.chatserver.Box box = 1;</code>
     */
    public Builder mergeBox(io.leego.chat.core.Box value) {
      if (boxBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          box_ != null &&
          box_ != io.leego.chat.core.Box.getDefaultInstance()) {
          getBoxBuilder().mergeFrom(value);
        } else {
          box_ = value;
        }
      } else {
        boxBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.chatserver.Box box = 1;</code>
     */
    public Builder clearBox() {
      bitField0_ = (bitField0_ & ~0x00000001);
      box_ = null;
      if (boxBuilder_ != null) {
        boxBuilder_.dispose();
        boxBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.chatserver.Box box = 1;</code>
     */
    public io.leego.chat.core.Box.Builder getBoxBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getBoxFieldBuilder().getBuilder();
    }
    /**
     * <code>.chatserver.Box box = 1;</code>
     */
    public io.leego.chat.core.BoxOrBuilder getBoxOrBuilder() {
      if (boxBuilder_ != null) {
        return boxBuilder_.getMessageOrBuilder();
      } else {
        return box_ == null ?
            io.leego.chat.core.Box.getDefaultInstance() : box_;
      }
    }
    /**
     * <code>.chatserver.Box box = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.leego.chat.core.Box, io.leego.chat.core.Box.Builder, io.leego.chat.core.BoxOrBuilder> 
        getBoxFieldBuilder() {
      if (boxBuilder_ == null) {
        boxBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.leego.chat.core.Box, io.leego.chat.core.Box.Builder, io.leego.chat.core.BoxOrBuilder>(
                getBox(),
                getParentForChildren(),
                isClean());
        box_ = null;
      }
      return boxBuilder_;
    }

    private com.google.protobuf.Internal.LongList target_ = emptyLongList();
    private void ensureTargetIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        target_ = mutableCopy(target_);
        bitField0_ |= 0x00000002;
      }
    }
    /**
     * <code>repeated int64 target = 2;</code>
     * @return A list containing the target.
     */
    public java.util.List<java.lang.Long>
        getTargetList() {
      return ((bitField0_ & 0x00000002) != 0) ?
               java.util.Collections.unmodifiableList(target_) : target_;
    }
    /**
     * <code>repeated int64 target = 2;</code>
     * @return The count of target.
     */
    public int getTargetCount() {
      return target_.size();
    }
    /**
     * <code>repeated int64 target = 2;</code>
     * @param index The index of the element to return.
     * @return The target at the given index.
     */
    public long getTarget(int index) {
      return target_.getLong(index);
    }
    /**
     * <code>repeated int64 target = 2;</code>
     * @param index The index to set the value at.
     * @param value The target to set.
     * @return This builder for chaining.
     */
    public Builder setTarget(
        int index, long value) {
      
      ensureTargetIsMutable();
      target_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 target = 2;</code>
     * @param value The target to add.
     * @return This builder for chaining.
     */
    public Builder addTarget(long value) {
      
      ensureTargetIsMutable();
      target_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 target = 2;</code>
     * @param values The target to add.
     * @return This builder for chaining.
     */
    public Builder addAllTarget(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureTargetIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, target_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 target = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTarget() {
      target_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList client_ = emptyIntList();
    private void ensureClientIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        client_ = mutableCopy(client_);
        bitField0_ |= 0x00000004;
      }
    }
    /**
     * <code>repeated int32 client = 3;</code>
     * @return A list containing the client.
     */
    public java.util.List<java.lang.Integer>
        getClientList() {
      return ((bitField0_ & 0x00000004) != 0) ?
               java.util.Collections.unmodifiableList(client_) : client_;
    }
    /**
     * <code>repeated int32 client = 3;</code>
     * @return The count of client.
     */
    public int getClientCount() {
      return client_.size();
    }
    /**
     * <code>repeated int32 client = 3;</code>
     * @param index The index of the element to return.
     * @return The client at the given index.
     */
    public int getClient(int index) {
      return client_.getInt(index);
    }
    /**
     * <code>repeated int32 client = 3;</code>
     * @param index The index to set the value at.
     * @param value The client to set.
     * @return This builder for chaining.
     */
    public Builder setClient(
        int index, int value) {
      
      ensureClientIsMutable();
      client_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 client = 3;</code>
     * @param value The client to add.
     * @return This builder for chaining.
     */
    public Builder addClient(int value) {
      
      ensureClientIsMutable();
      client_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 client = 3;</code>
     * @param values The client to add.
     * @return This builder for chaining.
     */
    public Builder addAllClient(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureClientIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, client_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 client = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearClient() {
      client_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:chatserver.Packet)
  }

  // @@protoc_insertion_point(class_scope:chatserver.Packet)
  private static final io.leego.chat.core.Packet DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.leego.chat.core.Packet();
  }

  public static io.leego.chat.core.Packet getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Packet>
      PARSER = new com.google.protobuf.AbstractParser<Packet>() {
    @java.lang.Override
    public Packet parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Packet> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Packet> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.leego.chat.core.Packet getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

