# name
spring.application.name=chat-server
# logging
logging.file.name=./logs/chat-server.log
logging.file.max-size=500MB
logging.file.max-history=30
logging.level.io.leego=debug
# chat
#chat.server.port=20000
#chat.server.idle-timeout=60s
#chat.server.auth-timeout=5s
#chat.server.path=/chat
