// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yihleego/chat/backend/ent/chatmate"
	"github.com/yihleego/chat/backend/ent/predicate"
)

// ChatmateUpdate is the builder for updating Chatmate entities.
type ChatmateUpdate struct {
	config
	hooks    []Hook
	mutation *ChatmateMutation
}

// Where appends a list predicates to the ChatmateUpdate builder.
func (cu *ChatmateUpdate) Where(ps ...predicate.Chatmate) *ChatmateUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetBizID sets the "biz_id" field.
func (cu *ChatmateUpdate) SetBizID(i int64) *ChatmateUpdate {
	cu.mutation.ResetBizID()
	cu.mutation.SetBizID(i)
	return cu
}

// AddBizID adds i to the "biz_id" field.
func (cu *ChatmateUpdate) AddBizID(i int64) *ChatmateUpdate {
	cu.mutation.AddBizID(i)
	return cu
}

// SetType sets the "type" field.
func (cu *ChatmateUpdate) SetType(i int32) *ChatmateUpdate {
	cu.mutation.ResetType()
	cu.mutation.SetType(i)
	return cu
}

// AddType adds i to the "type" field.
func (cu *ChatmateUpdate) AddType(i int32) *ChatmateUpdate {
	cu.mutation.AddType(i)
	return cu
}

// SetName sets the "name" field.
func (cu *ChatmateUpdate) SetName(s string) *ChatmateUpdate {
	cu.mutation.SetName(s)
	return cu
}

// SetAvatar sets the "avatar" field.
func (cu *ChatmateUpdate) SetAvatar(s string) *ChatmateUpdate {
	cu.mutation.SetAvatar(s)
	return cu
}

// SetLastMessageID sets the "last_message_id" field.
func (cu *ChatmateUpdate) SetLastMessageID(i int64) *ChatmateUpdate {
	cu.mutation.ResetLastMessageID()
	cu.mutation.SetLastMessageID(i)
	return cu
}

// AddLastMessageID adds i to the "last_message_id" field.
func (cu *ChatmateUpdate) AddLastMessageID(i int64) *ChatmateUpdate {
	cu.mutation.AddLastMessageID(i)
	return cu
}

// SetLastChatTime sets the "last_chat_time" field.
func (cu *ChatmateUpdate) SetLastChatTime(i int64) *ChatmateUpdate {
	cu.mutation.ResetLastChatTime()
	cu.mutation.SetLastChatTime(i)
	return cu
}

// AddLastChatTime adds i to the "last_chat_time" field.
func (cu *ChatmateUpdate) AddLastChatTime(i int64) *ChatmateUpdate {
	cu.mutation.AddLastChatTime(i)
	return cu
}

// Mutation returns the ChatmateMutation object of the builder.
func (cu *ChatmateUpdate) Mutation() *ChatmateMutation {
	return cu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *ChatmateUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(cu.hooks) == 0 {
		affected, err = cu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ChatmateMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cu.mutation = mutation
			affected, err = cu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cu.hooks) - 1; i >= 0; i-- {
			if cu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (cu *ChatmateUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *ChatmateUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *ChatmateUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cu *ChatmateUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   chatmate.Table,
			Columns: chatmate.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: chatmate.FieldID,
			},
		},
	}
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.BizID(); ok {
		_spec.SetField(chatmate.FieldBizID, field.TypeInt64, value)
	}
	if value, ok := cu.mutation.AddedBizID(); ok {
		_spec.AddField(chatmate.FieldBizID, field.TypeInt64, value)
	}
	if value, ok := cu.mutation.GetType(); ok {
		_spec.SetField(chatmate.FieldType, field.TypeInt32, value)
	}
	if value, ok := cu.mutation.AddedType(); ok {
		_spec.AddField(chatmate.FieldType, field.TypeInt32, value)
	}
	if value, ok := cu.mutation.Name(); ok {
		_spec.SetField(chatmate.FieldName, field.TypeString, value)
	}
	if value, ok := cu.mutation.Avatar(); ok {
		_spec.SetField(chatmate.FieldAvatar, field.TypeString, value)
	}
	if value, ok := cu.mutation.LastMessageID(); ok {
		_spec.SetField(chatmate.FieldLastMessageID, field.TypeInt64, value)
	}
	if value, ok := cu.mutation.AddedLastMessageID(); ok {
		_spec.AddField(chatmate.FieldLastMessageID, field.TypeInt64, value)
	}
	if value, ok := cu.mutation.LastChatTime(); ok {
		_spec.SetField(chatmate.FieldLastChatTime, field.TypeInt64, value)
	}
	if value, ok := cu.mutation.AddedLastChatTime(); ok {
		_spec.AddField(chatmate.FieldLastChatTime, field.TypeInt64, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatmate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// ChatmateUpdateOne is the builder for updating a single Chatmate entity.
type ChatmateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChatmateMutation
}

// SetBizID sets the "biz_id" field.
func (cuo *ChatmateUpdateOne) SetBizID(i int64) *ChatmateUpdateOne {
	cuo.mutation.ResetBizID()
	cuo.mutation.SetBizID(i)
	return cuo
}

// AddBizID adds i to the "biz_id" field.
func (cuo *ChatmateUpdateOne) AddBizID(i int64) *ChatmateUpdateOne {
	cuo.mutation.AddBizID(i)
	return cuo
}

// SetType sets the "type" field.
func (cuo *ChatmateUpdateOne) SetType(i int32) *ChatmateUpdateOne {
	cuo.mutation.ResetType()
	cuo.mutation.SetType(i)
	return cuo
}

// AddType adds i to the "type" field.
func (cuo *ChatmateUpdateOne) AddType(i int32) *ChatmateUpdateOne {
	cuo.mutation.AddType(i)
	return cuo
}

// SetName sets the "name" field.
func (cuo *ChatmateUpdateOne) SetName(s string) *ChatmateUpdateOne {
	cuo.mutation.SetName(s)
	return cuo
}

// SetAvatar sets the "avatar" field.
func (cuo *ChatmateUpdateOne) SetAvatar(s string) *ChatmateUpdateOne {
	cuo.mutation.SetAvatar(s)
	return cuo
}

// SetLastMessageID sets the "last_message_id" field.
func (cuo *ChatmateUpdateOne) SetLastMessageID(i int64) *ChatmateUpdateOne {
	cuo.mutation.ResetLastMessageID()
	cuo.mutation.SetLastMessageID(i)
	return cuo
}

// AddLastMessageID adds i to the "last_message_id" field.
func (cuo *ChatmateUpdateOne) AddLastMessageID(i int64) *ChatmateUpdateOne {
	cuo.mutation.AddLastMessageID(i)
	return cuo
}

// SetLastChatTime sets the "last_chat_time" field.
func (cuo *ChatmateUpdateOne) SetLastChatTime(i int64) *ChatmateUpdateOne {
	cuo.mutation.ResetLastChatTime()
	cuo.mutation.SetLastChatTime(i)
	return cuo
}

// AddLastChatTime adds i to the "last_chat_time" field.
func (cuo *ChatmateUpdateOne) AddLastChatTime(i int64) *ChatmateUpdateOne {
	cuo.mutation.AddLastChatTime(i)
	return cuo
}

// Mutation returns the ChatmateMutation object of the builder.
func (cuo *ChatmateUpdateOne) Mutation() *ChatmateMutation {
	return cuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *ChatmateUpdateOne) Select(field string, fields ...string) *ChatmateUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Chatmate entity.
func (cuo *ChatmateUpdateOne) Save(ctx context.Context) (*Chatmate, error) {
	var (
		err  error
		node *Chatmate
	)
	if len(cuo.hooks) == 0 {
		node, err = cuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ChatmateMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cuo.mutation = mutation
			node, err = cuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(cuo.hooks) - 1; i >= 0; i-- {
			if cuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, cuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Chatmate)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from ChatmateMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *ChatmateUpdateOne) SaveX(ctx context.Context) *Chatmate {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *ChatmateUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *ChatmateUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cuo *ChatmateUpdateOne) sqlSave(ctx context.Context) (_node *Chatmate, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   chatmate.Table,
			Columns: chatmate.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: chatmate.FieldID,
			},
		},
	}
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Chatmate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chatmate.FieldID)
		for _, f := range fields {
			if !chatmate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != chatmate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.BizID(); ok {
		_spec.SetField(chatmate.FieldBizID, field.TypeInt64, value)
	}
	if value, ok := cuo.mutation.AddedBizID(); ok {
		_spec.AddField(chatmate.FieldBizID, field.TypeInt64, value)
	}
	if value, ok := cuo.mutation.GetType(); ok {
		_spec.SetField(chatmate.FieldType, field.TypeInt32, value)
	}
	if value, ok := cuo.mutation.AddedType(); ok {
		_spec.AddField(chatmate.FieldType, field.TypeInt32, value)
	}
	if value, ok := cuo.mutation.Name(); ok {
		_spec.SetField(chatmate.FieldName, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Avatar(); ok {
		_spec.SetField(chatmate.FieldAvatar, field.TypeString, value)
	}
	if value, ok := cuo.mutation.LastMessageID(); ok {
		_spec.SetField(chatmate.FieldLastMessageID, field.TypeInt64, value)
	}
	if value, ok := cuo.mutation.AddedLastMessageID(); ok {
		_spec.AddField(chatmate.FieldLastMessageID, field.TypeInt64, value)
	}
	if value, ok := cuo.mutation.LastChatTime(); ok {
		_spec.SetField(chatmate.FieldLastChatTime, field.TypeInt64, value)
	}
	if value, ok := cuo.mutation.AddedLastChatTime(); ok {
		_spec.AddField(chatmate.FieldLastChatTime, field.TypeInt64, value)
	}
	_node = &Chatmate{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatmate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
