// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/yihleego/chat/backend/ent/conf"
)

// Conf is the model entity for the Conf schema.
type Conf struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Value holds the value of the "value" field.
	Value string `json:"value,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Conf) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case conf.FieldID, conf.FieldValue:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Conf", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Conf fields.
func (c *Conf) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case conf.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				c.ID = value.String
			}
		case conf.FieldValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				c.Value = value.String
			}
		}
	}
	return nil
}

// Update returns a builder for updating this Conf.
// Note that you need to call Conf.Unwrap() before calling this method if this Conf
// was returned from a transaction, and the transaction was committed or rolled back.
func (c *Conf) Update() *ConfUpdateOne {
	return (&ConfClient{config: c.config}).UpdateOne(c)
}

// Unwrap unwraps the Conf entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (c *Conf) Unwrap() *Conf {
	_tx, ok := c.config.driver.(*txDriver)
	if !ok {
		panic("ent: Conf is not a transactional entity")
	}
	c.config.driver = _tx.drv
	return c
}

// String implements the fmt.Stringer.
func (c *Conf) String() string {
	var builder strings.Builder
	builder.WriteString("Conf(")
	builder.WriteString(fmt.Sprintf("id=%v, ", c.ID))
	builder.WriteString("value=")
	builder.WriteString(c.Value)
	builder.WriteByte(')')
	return builder.String()
}

// Confs is a parsable slice of Conf.
type Confs []*Conf

func (c Confs) config(cfg config) {
	for _i := range c {
		c[_i].config = cfg
	}
}
