// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yihleego/chat/backend/ent/group"
	"github.com/yihleego/chat/backend/ent/predicate"
)

// GroupUpdate is the builder for updating Group entities.
type GroupUpdate struct {
	config
	hooks    []Hook
	mutation *GroupMutation
}

// Where appends a list predicates to the GroupUpdate builder.
func (gu *GroupUpdate) Where(ps ...predicate.Group) *GroupUpdate {
	gu.mutation.Where(ps...)
	return gu
}

// SetName sets the "name" field.
func (gu *GroupUpdate) SetName(s string) *GroupUpdate {
	gu.mutation.SetName(s)
	return gu
}

// SetAvatar sets the "avatar" field.
func (gu *GroupUpdate) SetAvatar(s string) *GroupUpdate {
	gu.mutation.SetAvatar(s)
	return gu
}

// SetOwner sets the "owner" field.
func (gu *GroupUpdate) SetOwner(i int64) *GroupUpdate {
	gu.mutation.ResetOwner()
	gu.mutation.SetOwner(i)
	return gu
}

// AddOwner adds i to the "owner" field.
func (gu *GroupUpdate) AddOwner(i int64) *GroupUpdate {
	gu.mutation.AddOwner(i)
	return gu
}

// SetSize sets the "size" field.
func (gu *GroupUpdate) SetSize(i int32) *GroupUpdate {
	gu.mutation.ResetSize()
	gu.mutation.SetSize(i)
	return gu
}

// AddSize adds i to the "size" field.
func (gu *GroupUpdate) AddSize(i int32) *GroupUpdate {
	gu.mutation.AddSize(i)
	return gu
}

// SetStatus sets the "status" field.
func (gu *GroupUpdate) SetStatus(i int32) *GroupUpdate {
	gu.mutation.ResetStatus()
	gu.mutation.SetStatus(i)
	return gu
}

// AddStatus adds i to the "status" field.
func (gu *GroupUpdate) AddStatus(i int32) *GroupUpdate {
	gu.mutation.AddStatus(i)
	return gu
}

// Mutation returns the GroupMutation object of the builder.
func (gu *GroupUpdate) Mutation() *GroupMutation {
	return gu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (gu *GroupUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(gu.hooks) == 0 {
		affected, err = gu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GroupMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			gu.mutation = mutation
			affected, err = gu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(gu.hooks) - 1; i >= 0; i-- {
			if gu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = gu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, gu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (gu *GroupUpdate) SaveX(ctx context.Context) int {
	affected, err := gu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (gu *GroupUpdate) Exec(ctx context.Context) error {
	_, err := gu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gu *GroupUpdate) ExecX(ctx context.Context) {
	if err := gu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (gu *GroupUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   group.Table,
			Columns: group.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: group.FieldID,
			},
		},
	}
	if ps := gu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := gu.mutation.Name(); ok {
		_spec.SetField(group.FieldName, field.TypeString, value)
	}
	if value, ok := gu.mutation.Avatar(); ok {
		_spec.SetField(group.FieldAvatar, field.TypeString, value)
	}
	if value, ok := gu.mutation.Owner(); ok {
		_spec.SetField(group.FieldOwner, field.TypeInt64, value)
	}
	if value, ok := gu.mutation.AddedOwner(); ok {
		_spec.AddField(group.FieldOwner, field.TypeInt64, value)
	}
	if value, ok := gu.mutation.Size(); ok {
		_spec.SetField(group.FieldSize, field.TypeInt32, value)
	}
	if value, ok := gu.mutation.AddedSize(); ok {
		_spec.AddField(group.FieldSize, field.TypeInt32, value)
	}
	if value, ok := gu.mutation.Status(); ok {
		_spec.SetField(group.FieldStatus, field.TypeInt32, value)
	}
	if value, ok := gu.mutation.AddedStatus(); ok {
		_spec.AddField(group.FieldStatus, field.TypeInt32, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, gu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{group.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// GroupUpdateOne is the builder for updating a single Group entity.
type GroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GroupMutation
}

// SetName sets the "name" field.
func (guo *GroupUpdateOne) SetName(s string) *GroupUpdateOne {
	guo.mutation.SetName(s)
	return guo
}

// SetAvatar sets the "avatar" field.
func (guo *GroupUpdateOne) SetAvatar(s string) *GroupUpdateOne {
	guo.mutation.SetAvatar(s)
	return guo
}

// SetOwner sets the "owner" field.
func (guo *GroupUpdateOne) SetOwner(i int64) *GroupUpdateOne {
	guo.mutation.ResetOwner()
	guo.mutation.SetOwner(i)
	return guo
}

// AddOwner adds i to the "owner" field.
func (guo *GroupUpdateOne) AddOwner(i int64) *GroupUpdateOne {
	guo.mutation.AddOwner(i)
	return guo
}

// SetSize sets the "size" field.
func (guo *GroupUpdateOne) SetSize(i int32) *GroupUpdateOne {
	guo.mutation.ResetSize()
	guo.mutation.SetSize(i)
	return guo
}

// AddSize adds i to the "size" field.
func (guo *GroupUpdateOne) AddSize(i int32) *GroupUpdateOne {
	guo.mutation.AddSize(i)
	return guo
}

// SetStatus sets the "status" field.
func (guo *GroupUpdateOne) SetStatus(i int32) *GroupUpdateOne {
	guo.mutation.ResetStatus()
	guo.mutation.SetStatus(i)
	return guo
}

// AddStatus adds i to the "status" field.
func (guo *GroupUpdateOne) AddStatus(i int32) *GroupUpdateOne {
	guo.mutation.AddStatus(i)
	return guo
}

// Mutation returns the GroupMutation object of the builder.
func (guo *GroupUpdateOne) Mutation() *GroupMutation {
	return guo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (guo *GroupUpdateOne) Select(field string, fields ...string) *GroupUpdateOne {
	guo.fields = append([]string{field}, fields...)
	return guo
}

// Save executes the query and returns the updated Group entity.
func (guo *GroupUpdateOne) Save(ctx context.Context) (*Group, error) {
	var (
		err  error
		node *Group
	)
	if len(guo.hooks) == 0 {
		node, err = guo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GroupMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			guo.mutation = mutation
			node, err = guo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(guo.hooks) - 1; i >= 0; i-- {
			if guo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = guo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, guo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Group)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from GroupMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (guo *GroupUpdateOne) SaveX(ctx context.Context) *Group {
	node, err := guo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (guo *GroupUpdateOne) Exec(ctx context.Context) error {
	_, err := guo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (guo *GroupUpdateOne) ExecX(ctx context.Context) {
	if err := guo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (guo *GroupUpdateOne) sqlSave(ctx context.Context) (_node *Group, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   group.Table,
			Columns: group.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: group.FieldID,
			},
		},
	}
	id, ok := guo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Group.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := guo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, group.FieldID)
		for _, f := range fields {
			if !group.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != group.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := guo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := guo.mutation.Name(); ok {
		_spec.SetField(group.FieldName, field.TypeString, value)
	}
	if value, ok := guo.mutation.Avatar(); ok {
		_spec.SetField(group.FieldAvatar, field.TypeString, value)
	}
	if value, ok := guo.mutation.Owner(); ok {
		_spec.SetField(group.FieldOwner, field.TypeInt64, value)
	}
	if value, ok := guo.mutation.AddedOwner(); ok {
		_spec.AddField(group.FieldOwner, field.TypeInt64, value)
	}
	if value, ok := guo.mutation.Size(); ok {
		_spec.SetField(group.FieldSize, field.TypeInt32, value)
	}
	if value, ok := guo.mutation.AddedSize(); ok {
		_spec.AddField(group.FieldSize, field.TypeInt32, value)
	}
	if value, ok := guo.mutation.Status(); ok {
		_spec.SetField(group.FieldStatus, field.TypeInt32, value)
	}
	if value, ok := guo.mutation.AddedStatus(); ok {
		_spec.AddField(group.FieldStatus, field.TypeInt32, value)
	}
	_node = &Group{config: guo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, guo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{group.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
