# port
server.port=10000
# name
spring.application.name=chat-api
# mongodb
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=chat_test
# logging
logging.file.name=./logs/chat-api.log
logging.file.max-size=500MB
logging.file.max-history=30
logging.level.io.leego=debug
