// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect() {
  return window['go']['chat']['Chat']['Connect']();
}

export function Debug(arg1) {
  return window['go']['chat']['Chat']['Debug'](arg1);
}

export function Debugf(arg1, arg2) {
  return window['go']['chat']['Chat']['Debugf'](arg1, arg2);
}

export function Dev() {
  return window['go']['chat']['Chat']['Dev']();
}

export function Disconnect() {
  return window['go']['chat']['Chat']['Disconnect']();
}

export function Error(arg1) {
  return window['go']['chat']['Chat']['Error'](arg1);
}

export function Errorf(arg1, arg2) {
  return window['go']['chat']['Chat']['Errorf'](arg1, arg2);
}

export function GetMessage(arg1) {
  return window['go']['chat']['Chat']['GetMessage'](arg1);
}

export function GetSession() {
  return window['go']['chat']['Chat']['GetSession']();
}

export function GetUser() {
  return window['go']['chat']['Chat']['GetUser']();
}

export function ReadMessages(arg1, arg2) {
  return window['go']['chat']['Chat']['ReadMessages'](arg1, arg2);
}

export function RevokeMessage(arg1) {
  return window['go']['chat']['Chat']['RevokeMessage'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['chat']['Chat']['SendMessage'](arg1);
}

export function SetLoginWindow() {
  return window['go']['chat']['Chat']['SetLoginWindow']();
}

export function SetMainWindow() {
  return window['go']['chat']['Chat']['SetMainWindow']();
}

export function Shutdown() {
  return window['go']['chat']['Chat']['Shutdown']();
}

export function SignIn(arg1) {
  return window['go']['chat']['Chat']['SignIn'](arg1);
}

export function SignOut() {
  return window['go']['chat']['Chat']['SignOut']();
}

export function SignUp(arg1) {
  return window['go']['chat']['Chat']['SignUp'](arg1);
}

export function Startup(arg1) {
  return window['go']['chat']['Chat']['Startup'](arg1);
}

export function Warn(arg1) {
  return window['go']['chat']['Chat']['Warn'](arg1);
}

export function Warnf(arg1, arg2) {
  return window['go']['chat']['Chat']['Warnf'](arg1, arg2);
}
