// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatapi.proto

package io.leego.chat.core;

public final class ChatFactory {
  private ChatFactory() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chatapi_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chatapi_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chatapi_Messages_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chatapi_Messages_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chatapi_GroupMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chatapi_GroupMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chatapi_Mention_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chatapi_Mention_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chatapi_GroupMessages_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chatapi_GroupMessages_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chatapi_Instance_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chatapi_Instance_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rchatapi.proto\022\007chatapi\"\227\001\n\007Message\022\n\n\002" +
      "id\030\001 \001(\003\022\016\n\006sender\030\002 \001(\003\022\021\n\trecipient\030\003 " +
      "\001(\003\022\020\n\010sentTime\030\004 \001(\003\022\014\n\004type\030\005 \001(\005\022\017\n\007c" +
      "ontent\030\006 \001(\t\022\r\n\005taken\030\007 \001(\010\022\014\n\004seen\030\010 \001(" +
      "\010\022\017\n\007revoked\030\t \001(\010\"-\n\010Messages\022!\n\007messag" +
      "e\030\001 \003(\0132\020.chatapi.Message\"\340\001\n\014GroupMessa" +
      "ge\022\n\n\002id\030\001 \001(\003\022\017\n\007groupId\030\002 \001(\003\022\016\n\006sende" +
      "r\030\003 \001(\003\022\021\n\trecipient\030\004 \001(\003\022\020\n\010sentTime\030\005" +
      " \001(\003\022\014\n\004type\030\006 \001(\005\022\017\n\007content\030\007 \001(\t\022\r\n\005t" +
      "aken\030\010 \001(\010\022\014\n\004seen\030\t \001(\010\022\017\n\007revoked\030\n \001(" +
      "\010\022!\n\007mention\030\013 \003(\0132\020.chatapi.Mention\022\016\n\006" +
      "status\030\014 \001(\005\"(\n\007Mention\022\016\n\006userId\030\001 \001(\003\022" +
      "\r\n\005index\030\002 \001(\005\"7\n\rGroupMessages\022&\n\007messa" +
      "ge\030\001 \003(\0132\025.chatapi.GroupMessage\"\246\001\n\010Inst" +
      "ance\022\014\n\004node\030\001 \001(\005\022\021\n\ttimestamp\030\002 \001(\003\022\014\n" +
      "\004host\030\003 \001(\t\022\025\n\rdiscoveryPort\030\004 \001(\005\022\017\n\007ra" +
      "wPort\030\005 \001(\005\022\016\n\006wsPort\030\006 \001(\005\022\017\n\007clients\030\007" +
      " \001(\005\022\017\n\007leaders\030\010 \001(\005\022\021\n\tfollowers\030\t \001(\005" +
      "B#\n\022io.leego.chat.coreB\013ChatFactoryP\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_chatapi_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_chatapi_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chatapi_Message_descriptor,
        new java.lang.String[] { "Id", "Sender", "Recipient", "SentTime", "Type", "Content", "Taken", "Seen", "Revoked", });
    internal_static_chatapi_Messages_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_chatapi_Messages_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chatapi_Messages_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_chatapi_GroupMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_chatapi_GroupMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chatapi_GroupMessage_descriptor,
        new java.lang.String[] { "Id", "GroupId", "Sender", "Recipient", "SentTime", "Type", "Content", "Taken", "Seen", "Revoked", "Mention", "Status", });
    internal_static_chatapi_Mention_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_chatapi_Mention_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chatapi_Mention_descriptor,
        new java.lang.String[] { "UserId", "Index", });
    internal_static_chatapi_GroupMessages_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_chatapi_GroupMessages_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chatapi_GroupMessages_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_chatapi_Instance_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_chatapi_Instance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chatapi_Instance_descriptor,
        new java.lang.String[] { "Node", "Timestamp", "Host", "DiscoveryPort", "RawPort", "WsPort", "Clients", "Leaders", "Followers", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
