// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatapi.proto

package io.leego.chat.core;

/**
 * Protobuf type {@code chatapi.GroupMessage}
 */
public final class GroupMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:chatapi.GroupMessage)
    GroupMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GroupMessage.newBuilder() to construct.
  private GroupMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GroupMessage() {
    content_ = "";
    mention_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GroupMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.leego.chat.core.ChatFactory.internal_static_chatapi_GroupMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.leego.chat.core.ChatFactory.internal_static_chatapi_GroupMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.leego.chat.core.GroupMessage.class, io.leego.chat.core.GroupMessage.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_ = 0L;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int GROUPID_FIELD_NUMBER = 2;
  private long groupId_ = 0L;
  /**
   * <code>int64 groupId = 2;</code>
   * @return The groupId.
   */
  @java.lang.Override
  public long getGroupId() {
    return groupId_;
  }

  public static final int SENDER_FIELD_NUMBER = 3;
  private long sender_ = 0L;
  /**
   * <code>int64 sender = 3;</code>
   * @return The sender.
   */
  @java.lang.Override
  public long getSender() {
    return sender_;
  }

  public static final int RECIPIENT_FIELD_NUMBER = 4;
  private long recipient_ = 0L;
  /**
   * <code>int64 recipient = 4;</code>
   * @return The recipient.
   */
  @java.lang.Override
  public long getRecipient() {
    return recipient_;
  }

  public static final int SENTTIME_FIELD_NUMBER = 5;
  private long sentTime_ = 0L;
  /**
   * <code>int64 sentTime = 5;</code>
   * @return The sentTime.
   */
  @java.lang.Override
  public long getSentTime() {
    return sentTime_;
  }

  public static final int TYPE_FIELD_NUMBER = 6;
  private int type_ = 0;
  /**
   * <code>int32 type = 6;</code>
   * @return The type.
   */
  @java.lang.Override
  public int getType() {
    return type_;
  }

  public static final int CONTENT_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object content_ = "";
  /**
   * <code>string content = 7;</code>
   * @return The content.
   */
  @java.lang.Override
  public java.lang.String getContent() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      content_ = s;
      return s;
    }
  }
  /**
   * <code>string content = 7;</code>
   * @return The bytes for content.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContentBytes() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      content_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TAKEN_FIELD_NUMBER = 8;
  private boolean taken_ = false;
  /**
   * <code>bool taken = 8;</code>
   * @return The taken.
   */
  @java.lang.Override
  public boolean getTaken() {
    return taken_;
  }

  public static final int SEEN_FIELD_NUMBER = 9;
  private boolean seen_ = false;
  /**
   * <code>bool seen = 9;</code>
   * @return The seen.
   */
  @java.lang.Override
  public boolean getSeen() {
    return seen_;
  }

  public static final int REVOKED_FIELD_NUMBER = 10;
  private boolean revoked_ = false;
  /**
   * <code>bool revoked = 10;</code>
   * @return The revoked.
   */
  @java.lang.Override
  public boolean getRevoked() {
    return revoked_;
  }

  public static final int MENTION_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private java.util.List<io.leego.chat.core.Mention> mention_;
  /**
   * <code>repeated .chatapi.Mention mention = 11;</code>
   */
  @java.lang.Override
  public java.util.List<io.leego.chat.core.Mention> getMentionList() {
    return mention_;
  }
  /**
   * <code>repeated .chatapi.Mention mention = 11;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.leego.chat.core.MentionOrBuilder> 
      getMentionOrBuilderList() {
    return mention_;
  }
  /**
   * <code>repeated .chatapi.Mention mention = 11;</code>
   */
  @java.lang.Override
  public int getMentionCount() {
    return mention_.size();
  }
  /**
   * <code>repeated .chatapi.Mention mention = 11;</code>
   */
  @java.lang.Override
  public io.leego.chat.core.Mention getMention(int index) {
    return mention_.get(index);
  }
  /**
   * <code>repeated .chatapi.Mention mention = 11;</code>
   */
  @java.lang.Override
  public io.leego.chat.core.MentionOrBuilder getMentionOrBuilder(
      int index) {
    return mention_.get(index);
  }

  public static final int STATUS_FIELD_NUMBER = 12;
  private int status_ = 0;
  /**
   * <code>int32 status = 12;</code>
   * @return The status.
   */
  @java.lang.Override
  public int getStatus() {
    return status_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (groupId_ != 0L) {
      output.writeInt64(2, groupId_);
    }
    if (sender_ != 0L) {
      output.writeInt64(3, sender_);
    }
    if (recipient_ != 0L) {
      output.writeInt64(4, recipient_);
    }
    if (sentTime_ != 0L) {
      output.writeInt64(5, sentTime_);
    }
    if (type_ != 0) {
      output.writeInt32(6, type_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, content_);
    }
    if (taken_ != false) {
      output.writeBool(8, taken_);
    }
    if (seen_ != false) {
      output.writeBool(9, seen_);
    }
    if (revoked_ != false) {
      output.writeBool(10, revoked_);
    }
    for (int i = 0; i < mention_.size(); i++) {
      output.writeMessage(11, mention_.get(i));
    }
    if (status_ != 0) {
      output.writeInt32(12, status_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (groupId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, groupId_);
    }
    if (sender_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, sender_);
    }
    if (recipient_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, recipient_);
    }
    if (sentTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, sentTime_);
    }
    if (type_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, type_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, content_);
    }
    if (taken_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, taken_);
    }
    if (seen_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(9, seen_);
    }
    if (revoked_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, revoked_);
    }
    for (int i = 0; i < mention_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, mention_.get(i));
    }
    if (status_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(12, status_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.leego.chat.core.GroupMessage)) {
      return super.equals(obj);
    }
    io.leego.chat.core.GroupMessage other = (io.leego.chat.core.GroupMessage) obj;

    if (getId()
        != other.getId()) return false;
    if (getGroupId()
        != other.getGroupId()) return false;
    if (getSender()
        != other.getSender()) return false;
    if (getRecipient()
        != other.getRecipient()) return false;
    if (getSentTime()
        != other.getSentTime()) return false;
    if (getType()
        != other.getType()) return false;
    if (!getContent()
        .equals(other.getContent())) return false;
    if (getTaken()
        != other.getTaken()) return false;
    if (getSeen()
        != other.getSeen()) return false;
    if (getRevoked()
        != other.getRevoked()) return false;
    if (!getMentionList()
        .equals(other.getMentionList())) return false;
    if (getStatus()
        != other.getStatus()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + GROUPID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getGroupId());
    hash = (37 * hash) + SENDER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSender());
    hash = (37 * hash) + RECIPIENT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRecipient());
    hash = (37 * hash) + SENTTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSentTime());
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType();
    hash = (37 * hash) + CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getContent().hashCode();
    hash = (37 * hash) + TAKEN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getTaken());
    hash = (37 * hash) + SEEN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSeen());
    hash = (37 * hash) + REVOKED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getRevoked());
    if (getMentionCount() > 0) {
      hash = (37 * hash) + MENTION_FIELD_NUMBER;
      hash = (53 * hash) + getMentionList().hashCode();
    }
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.leego.chat.core.GroupMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.leego.chat.core.GroupMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.leego.chat.core.GroupMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.leego.chat.core.GroupMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.leego.chat.core.GroupMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.leego.chat.core.GroupMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.leego.chat.core.GroupMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.leego.chat.core.GroupMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.leego.chat.core.GroupMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.leego.chat.core.GroupMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.leego.chat.core.GroupMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.leego.chat.core.GroupMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.leego.chat.core.GroupMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code chatapi.GroupMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:chatapi.GroupMessage)
      io.leego.chat.core.GroupMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.leego.chat.core.ChatFactory.internal_static_chatapi_GroupMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.leego.chat.core.ChatFactory.internal_static_chatapi_GroupMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.leego.chat.core.GroupMessage.class, io.leego.chat.core.GroupMessage.Builder.class);
    }

    // Construct using io.leego.chat.core.GroupMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0L;
      groupId_ = 0L;
      sender_ = 0L;
      recipient_ = 0L;
      sentTime_ = 0L;
      type_ = 0;
      content_ = "";
      taken_ = false;
      seen_ = false;
      revoked_ = false;
      if (mentionBuilder_ == null) {
        mention_ = java.util.Collections.emptyList();
      } else {
        mention_ = null;
        mentionBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000400);
      status_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.leego.chat.core.ChatFactory.internal_static_chatapi_GroupMessage_descriptor;
    }

    @java.lang.Override
    public io.leego.chat.core.GroupMessage getDefaultInstanceForType() {
      return io.leego.chat.core.GroupMessage.getDefaultInstance();
    }

    @java.lang.Override
    public io.leego.chat.core.GroupMessage build() {
      io.leego.chat.core.GroupMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.leego.chat.core.GroupMessage buildPartial() {
      io.leego.chat.core.GroupMessage result = new io.leego.chat.core.GroupMessage(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.leego.chat.core.GroupMessage result) {
      if (mentionBuilder_ == null) {
        if (((bitField0_ & 0x00000400) != 0)) {
          mention_ = java.util.Collections.unmodifiableList(mention_);
          bitField0_ = (bitField0_ & ~0x00000400);
        }
        result.mention_ = mention_;
      } else {
        result.mention_ = mentionBuilder_.build();
      }
    }

    private void buildPartial0(io.leego.chat.core.GroupMessage result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.groupId_ = groupId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.sender_ = sender_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.recipient_ = recipient_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.sentTime_ = sentTime_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.content_ = content_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.taken_ = taken_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.seen_ = seen_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.revoked_ = revoked_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.status_ = status_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.leego.chat.core.GroupMessage) {
        return mergeFrom((io.leego.chat.core.GroupMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.leego.chat.core.GroupMessage other) {
      if (other == io.leego.chat.core.GroupMessage.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.getGroupId() != 0L) {
        setGroupId(other.getGroupId());
      }
      if (other.getSender() != 0L) {
        setSender(other.getSender());
      }
      if (other.getRecipient() != 0L) {
        setRecipient(other.getRecipient());
      }
      if (other.getSentTime() != 0L) {
        setSentTime(other.getSentTime());
      }
      if (other.getType() != 0) {
        setType(other.getType());
      }
      if (!other.getContent().isEmpty()) {
        content_ = other.content_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (other.getTaken() != false) {
        setTaken(other.getTaken());
      }
      if (other.getSeen() != false) {
        setSeen(other.getSeen());
      }
      if (other.getRevoked() != false) {
        setRevoked(other.getRevoked());
      }
      if (mentionBuilder_ == null) {
        if (!other.mention_.isEmpty()) {
          if (mention_.isEmpty()) {
            mention_ = other.mention_;
            bitField0_ = (bitField0_ & ~0x00000400);
          } else {
            ensureMentionIsMutable();
            mention_.addAll(other.mention_);
          }
          onChanged();
        }
      } else {
        if (!other.mention_.isEmpty()) {
          if (mentionBuilder_.isEmpty()) {
            mentionBuilder_.dispose();
            mentionBuilder_ = null;
            mention_ = other.mention_;
            bitField0_ = (bitField0_ & ~0x00000400);
            mentionBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMentionFieldBuilder() : null;
          } else {
            mentionBuilder_.addAllMessages(other.mention_);
          }
        }
      }
      if (other.getStatus() != 0) {
        setStatus(other.getStatus());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              groupId_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              sender_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              recipient_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              sentTime_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              type_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              content_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 64: {
              taken_ = input.readBool();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              seen_ = input.readBool();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 80: {
              revoked_ = input.readBool();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            case 90: {
              io.leego.chat.core.Mention m =
                  input.readMessage(
                      io.leego.chat.core.Mention.parser(),
                      extensionRegistry);
              if (mentionBuilder_ == null) {
                ensureMentionIsMutable();
                mention_.add(m);
              } else {
                mentionBuilder_.addMessage(m);
              }
              break;
            } // case 90
            case 96: {
              status_ = input.readInt32();
              bitField0_ |= 0x00000800;
              break;
            } // case 96
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0L;
      onChanged();
      return this;
    }

    private long groupId_ ;
    /**
     * <code>int64 groupId = 2;</code>
     * @return The groupId.
     */
    @java.lang.Override
    public long getGroupId() {
      return groupId_;
    }
    /**
     * <code>int64 groupId = 2;</code>
     * @param value The groupId to set.
     * @return This builder for chaining.
     */
    public Builder setGroupId(long value) {
      
      groupId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 groupId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearGroupId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      groupId_ = 0L;
      onChanged();
      return this;
    }

    private long sender_ ;
    /**
     * <code>int64 sender = 3;</code>
     * @return The sender.
     */
    @java.lang.Override
    public long getSender() {
      return sender_;
    }
    /**
     * <code>int64 sender = 3;</code>
     * @param value The sender to set.
     * @return This builder for chaining.
     */
    public Builder setSender(long value) {
      
      sender_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 sender = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSender() {
      bitField0_ = (bitField0_ & ~0x00000004);
      sender_ = 0L;
      onChanged();
      return this;
    }

    private long recipient_ ;
    /**
     * <code>int64 recipient = 4;</code>
     * @return The recipient.
     */
    @java.lang.Override
    public long getRecipient() {
      return recipient_;
    }
    /**
     * <code>int64 recipient = 4;</code>
     * @param value The recipient to set.
     * @return This builder for chaining.
     */
    public Builder setRecipient(long value) {
      
      recipient_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int64 recipient = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRecipient() {
      bitField0_ = (bitField0_ & ~0x00000008);
      recipient_ = 0L;
      onChanged();
      return this;
    }

    private long sentTime_ ;
    /**
     * <code>int64 sentTime = 5;</code>
     * @return The sentTime.
     */
    @java.lang.Override
    public long getSentTime() {
      return sentTime_;
    }
    /**
     * <code>int64 sentTime = 5;</code>
     * @param value The sentTime to set.
     * @return This builder for chaining.
     */
    public Builder setSentTime(long value) {
      
      sentTime_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int64 sentTime = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSentTime() {
      bitField0_ = (bitField0_ & ~0x00000010);
      sentTime_ = 0L;
      onChanged();
      return this;
    }

    private int type_ ;
    /**
     * <code>int32 type = 6;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }
    /**
     * <code>int32 type = 6;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(int value) {
      
      type_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 type = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000020);
      type_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object content_ = "";
    /**
     * <code>string content = 7;</code>
     * @return The content.
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string content = 7;</code>
     * @return The bytes for content.
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string content = 7;</code>
     * @param value The content to set.
     * @return This builder for chaining.
     */
    public Builder setContent(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      content_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string content = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearContent() {
      content_ = getDefaultInstance().getContent();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string content = 7;</code>
     * @param value The bytes for content to set.
     * @return This builder for chaining.
     */
    public Builder setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      content_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private boolean taken_ ;
    /**
     * <code>bool taken = 8;</code>
     * @return The taken.
     */
    @java.lang.Override
    public boolean getTaken() {
      return taken_;
    }
    /**
     * <code>bool taken = 8;</code>
     * @param value The taken to set.
     * @return This builder for chaining.
     */
    public Builder setTaken(boolean value) {
      
      taken_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>bool taken = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearTaken() {
      bitField0_ = (bitField0_ & ~0x00000080);
      taken_ = false;
      onChanged();
      return this;
    }

    private boolean seen_ ;
    /**
     * <code>bool seen = 9;</code>
     * @return The seen.
     */
    @java.lang.Override
    public boolean getSeen() {
      return seen_;
    }
    /**
     * <code>bool seen = 9;</code>
     * @param value The seen to set.
     * @return This builder for chaining.
     */
    public Builder setSeen(boolean value) {
      
      seen_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>bool seen = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeen() {
      bitField0_ = (bitField0_ & ~0x00000100);
      seen_ = false;
      onChanged();
      return this;
    }

    private boolean revoked_ ;
    /**
     * <code>bool revoked = 10;</code>
     * @return The revoked.
     */
    @java.lang.Override
    public boolean getRevoked() {
      return revoked_;
    }
    /**
     * <code>bool revoked = 10;</code>
     * @param value The revoked to set.
     * @return This builder for chaining.
     */
    public Builder setRevoked(boolean value) {
      
      revoked_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>bool revoked = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearRevoked() {
      bitField0_ = (bitField0_ & ~0x00000200);
      revoked_ = false;
      onChanged();
      return this;
    }

    private java.util.List<io.leego.chat.core.Mention> mention_ =
      java.util.Collections.emptyList();
    private void ensureMentionIsMutable() {
      if (!((bitField0_ & 0x00000400) != 0)) {
        mention_ = new java.util.ArrayList<io.leego.chat.core.Mention>(mention_);
        bitField0_ |= 0x00000400;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.leego.chat.core.Mention, io.leego.chat.core.Mention.Builder, io.leego.chat.core.MentionOrBuilder> mentionBuilder_;

    /**
     * <code>repeated .chatapi.Mention mention = 11;</code>
     */
    public java.util.List<io.leego.chat.core.Mention> getMentionList() {
      if (mentionBuilder_ == null) {
        return java.util.Collections.unmodifiableList(mention_);
      } else {
        return mentionBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .chatapi.Mention mention = 11;</code>
     */
    public int getMentionCount() {
      if (mentionBuilder_ == null) {
        return mention_.size();
      } else {
        return mentionBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .chatapi.Mention mention = 11;</code>
     */
    public io.leego.chat.core.Mention getMention(int index) {
      if (mentionBuilder_ == null) {
        return mention_.get(index);
      } else {
        return mentionBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .chatapi.Mention mention = 11;</code>
     */
    public Builder setMention(
        int index, io.leego.chat.core.Mention value) {
      if (mentionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMentionIsMutable();
        mention_.set(index, value);
        onChanged();
      } else {
        mentionBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .chatapi.Mention mention = 11;</code>
     */
    public Builder setMention(
        int index, io.leego.chat.core.Mention.Builder builderForValue) {
      if (mentionBuilder_ == null) {
        ensureMentionIsMutable();
        mention_.set(index, builderForValue.build());
        onChanged();
      } else {
        mentionBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .chatapi.Mention mention = 11;</code>
     */
    public Builder addMention(io.leego.chat.core.Mention value) {
      if (mentionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMentionIsMutable();
        mention_.add(value);
        onChanged();
      } else {
        mentionBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .chatapi.Mention mention = 11;</code>
     */
    public Builder addMention(
        int index, io.leego.chat.core.Mention value) {
      if (mentionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMentionIsMutable();
        mention_.add(index, value);
        onChanged();
      } else {
        mentionBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .chatapi.Mention mention = 11;</code>
     */
    public Builder addMention(
        io.leego.chat.core.Mention.Builder builderForValue) {
      if (mentionBuilder_ == null) {
        ensureMentionIsMutable();
        mention_.add(builderForValue.build());
        onChanged();
      } else {
        mentionBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .chatapi.Mention mention = 11;</code>
     */
    public Builder addMention(
        int index, io.leego.chat.core.Mention.Builder builderForValue) {
      if (mentionBuilder_ == null) {
        ensureMentionIsMutable();
        mention_.add(index, builderForValue.build());
        onChanged();
      } else {
        mentionBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .chatapi.Mention mention = 11;</code>
     */
    public Builder addAllMention(
        java.lang.Iterable<? extends io.leego.chat.core.Mention> values) {
      if (mentionBuilder_ == null) {
        ensureMentionIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, mention_);
        onChanged();
      } else {
        mentionBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .chatapi.Mention mention = 11;</code>
     */
    public Builder clearMention() {
      if (mentionBuilder_ == null) {
        mention_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000400);
        onChanged();
      } else {
        mentionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .chatapi.Mention mention = 11;</code>
     */
    public Builder removeMention(int index) {
      if (mentionBuilder_ == null) {
        ensureMentionIsMutable();
        mention_.remove(index);
        onChanged();
      } else {
        mentionBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .chatapi.Mention mention = 11;</code>
     */
    public io.leego.chat.core.Mention.Builder getMentionBuilder(
        int index) {
      return getMentionFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .chatapi.Mention mention = 11;</code>
     */
    public io.leego.chat.core.MentionOrBuilder getMentionOrBuilder(
        int index) {
      if (mentionBuilder_ == null) {
        return mention_.get(index);  } else {
        return mentionBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .chatapi.Mention mention = 11;</code>
     */
    public java.util.List<? extends io.leego.chat.core.MentionOrBuilder> 
         getMentionOrBuilderList() {
      if (mentionBuilder_ != null) {
        return mentionBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(mention_);
      }
    }
    /**
     * <code>repeated .chatapi.Mention mention = 11;</code>
     */
    public io.leego.chat.core.Mention.Builder addMentionBuilder() {
      return getMentionFieldBuilder().addBuilder(
          io.leego.chat.core.Mention.getDefaultInstance());
    }
    /**
     * <code>repeated .chatapi.Mention mention = 11;</code>
     */
    public io.leego.chat.core.Mention.Builder addMentionBuilder(
        int index) {
      return getMentionFieldBuilder().addBuilder(
          index, io.leego.chat.core.Mention.getDefaultInstance());
    }
    /**
     * <code>repeated .chatapi.Mention mention = 11;</code>
     */
    public java.util.List<io.leego.chat.core.Mention.Builder> 
         getMentionBuilderList() {
      return getMentionFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.leego.chat.core.Mention, io.leego.chat.core.Mention.Builder, io.leego.chat.core.MentionOrBuilder> 
        getMentionFieldBuilder() {
      if (mentionBuilder_ == null) {
        mentionBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.leego.chat.core.Mention, io.leego.chat.core.Mention.Builder, io.leego.chat.core.MentionOrBuilder>(
                mention_,
                ((bitField0_ & 0x00000400) != 0),
                getParentForChildren(),
                isClean());
        mention_ = null;
      }
      return mentionBuilder_;
    }

    private int status_ ;
    /**
     * <code>int32 status = 12;</code>
     * @return The status.
     */
    @java.lang.Override
    public int getStatus() {
      return status_;
    }
    /**
     * <code>int32 status = 12;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(int value) {
      
      status_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>int32 status = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000800);
      status_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:chatapi.GroupMessage)
  }

  // @@protoc_insertion_point(class_scope:chatapi.GroupMessage)
  private static final io.leego.chat.core.GroupMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.leego.chat.core.GroupMessage();
  }

  public static io.leego.chat.core.GroupMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GroupMessage>
      PARSER = new com.google.protobuf.AbstractParser<GroupMessage>() {
    @java.lang.Override
    public GroupMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GroupMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GroupMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.leego.chat.core.GroupMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

