// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatapi.proto

package io.leego.chat.core;

public interface GroupMessagesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chatapi.GroupMessages)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .chatapi.GroupMessage message = 1;</code>
   */
  java.util.List<io.leego.chat.core.GroupMessage> 
      getMessageList();
  /**
   * <code>repeated .chatapi.GroupMessage message = 1;</code>
   */
  io.leego.chat.core.GroupMessage getMessage(int index);
  /**
   * <code>repeated .chatapi.GroupMessage message = 1;</code>
   */
  int getMessageCount();
  /**
   * <code>repeated .chatapi.GroupMessage message = 1;</code>
   */
  java.util.List<? extends io.leego.chat.core.GroupMessageOrBuilder> 
      getMessageOrBuilderList();
  /**
   * <code>repeated .chatapi.GroupMessage message = 1;</code>
   */
  io.leego.chat.core.GroupMessageOrBuilder getMessageOrBuilder(
      int index);
}
