// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatapi.proto

package io.leego.chat.core;

public interface MessagesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chatapi.Messages)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .chatapi.Message message = 1;</code>
   */
  java.util.List<io.leego.chat.core.Message> 
      getMessageList();
  /**
   * <code>repeated .chatapi.Message message = 1;</code>
   */
  io.leego.chat.core.Message getMessage(int index);
  /**
   * <code>repeated .chatapi.Message message = 1;</code>
   */
  int getMessageCount();
  /**
   * <code>repeated .chatapi.Message message = 1;</code>
   */
  java.util.List<? extends io.leego.chat.core.MessageOrBuilder> 
      getMessageOrBuilderList();
  /**
   * <code>repeated .chatapi.Message message = 1;</code>
   */
  io.leego.chat.core.MessageOrBuilder getMessageOrBuilder(
      int index);
}
