# name
spring.application.name=chat-client
# logging
logging.file.name=./logs/chat-client.log
logging.file.max-size=500MB
logging.file.max-history=30
logging.level.io.leego=debug
# chat
chat.client.host=localhost
chat.client.port=20000
chat.client.idle-timeout=10s
