// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Chatmate is the predicate function for chatmate builders.
type Chatmate func(*sql.Selector)

// Conf is the predicate function for conf builders.
type Conf func(*sql.Selector)

// Contact is the predicate function for contact builders.
type Contact func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// GroupMessage is the predicate function for groupmessage builders.
type GroupMessage func(*sql.Selector)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)
